# Generated by Django 3.2.3 on 2021-06-19 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=150)),
                ('CID', models.IntegerField(unique=True)),
                ('Units', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(100)])),
                ('Amount', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(100)])),
                ('BillGenerated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
